### ISSUE TITLE
Do "collision detection" on activity labels

### ISSUE THREAD

**Issue by waxlamp** [Kitware/dive#1000]
**Is your feature request related to a problem? If so, Please describe.**
When several annotations exist in the same part of the video frame, the activity labels become impossible to read because they are overlaid on each other.

**Describe the solution you'd like**
Show the labels spread out in space so they are all readable.

It could also be helpful to show these labels only on hover.

**Comment by BryonLewis** [comment]
I believe a tooltip (where the layer is naturally above the annotations) would work best for this.  Otherwise we can't guarantee that wherever the data is placed on the annotation layer that there won't be conflicts without checking every other annotation on the screen.

Linking for reference for tooltip implementation : https://github.com/OpenGeoscience/geojs/blob/master/examples/rainfall/main.js - this example of geoJS using DOM tooltips.

There are some specifics we may want to discuss:
- Is this a layer view like the others (rect, poly, line, text)?  
- Or is it a thing that only comes up automatically when the text layer is turned off?  
- Or is it a more universal setting?
