### ISSUE TITLE
[FEATURE] Desktop MultiCam Pipeline Support

### ISSUE THREAD

**Issue by BryonLewis** [Kitware/dive#1019]
MultiCamera support for desktop pipelines.

For testing purposes this requires the SEAL add-ons for VIAME:[ Sea Lion Models](https://data.kitware.com/api/v1/item/6011b1bc2fa25629b91a5e3c/download)
3- Camera Dataset sample: [SeaLions.zip](https://viame.kitware.com/girder#item/60b7b1993301d26fd683578c)

There are a series of multicam pipes in there, {detector|tracker}-{description}-{2|3}-cam.pipe, which are supposedly for 2 or 3 multicam datapoints.

Implementation Process:

- Confirm inputs/outputs are the same as other pipes and stereo pipes
- Confirm running pipes will produce valid csv results that can be displayed
- Look for alternatives besides RegEx matching for multicam pipelines.  See if there is a better way to make this work.
- If individual pipelines need to be ran this will need to be enabled in the pipeline display tool.

**Comment by neal-siekierski** [comment]
I can answer a couple of these:

> * There is an off by 1 issue with the result tracks where they start at frame 1 instead of frame 0.

The pipelines you mention don't include the downsampler. It turns out that the image list reader proper counts from 1 while the downsampler counts from 0. This is probably the cause of the issue, and I suspect the right fix here is to add the downsampler to these pipelines.

> * How strict is the 2 or 3 camera pipelines?  Should those only be enabled for the corresponding number of cameras?

The n-camera pipelines require n input files (for the `input{i}` processes) and produce n output files (from the `write_tracks_{i}` processes).

**Comment by BryonLewis** [comment]
@neal-siekierski thank for the response on those.

I noticed some additional things the other day when running the pipelines as well:
I ran the `supressor_sea_lion_3-cam.pipe`  but this one would only give me one camera field back with detections instead of all three.

I also ran `tracker_sea_lion_3-cam.pipe`  this one would give me detections for all 3 cameras.

I'm using similar input args for each and checking the outputs in the directory where it is complete.  Not entirely sure what the 'supressor' part means in the one, but I'm at least getting results back for a single camera with that one.

**Comment by neal-siekierski** [comment]
I've created updated versions of the pipelines and uploaded them: [`pipes_with_downsampler.zip`](https://github.com/Kitware/dive/files/7644259/pipes_with_downsampler.zip)

These include the downsampler (or rather downsampler*s*, one per camera as `downsampler{i}`), and following a suggestion from Matt D. to make process names more similar across pipelines, also have `track_writer{i}` instead of `write_tracks_{i}`. If these work, I'll ask Matt D. to update the add-on.

As for the difference between the pipelines, that sounds about right. The documentation is admittedly lacking. Briefly: the context is that these were created in the context of trying to count sea lions. The tracker pipelines do that by creating cross-camera tracks &ndash; then you can count the sea lions by counting unique track IDs. Unfortunately the stabilization method used (homographies) doesn't work amazingly on this data, so the tracker will create new tracks on the same sea lions. The suppressor is an approach to avoid double-counting via a fairly crude heuristic &ndash; if a detection falls anywhere within the bounding box of a previous\* *image*, it's just dropped / suppressed. No actual tracking is done. Then you get your count by counting the detections, and so ideally there's only ever one detection per sea lion.

\*  Technically, from any camera on the previous frame or an "earlier" camera on the same frame
