### ISSUE TITLE
Scripting Asset Loading

### ISSUE THREAD

**Issue by SiftingSands** [Kitware/dive#1342]
Is it possible to load videos and pre-annotations by running a script instead of manually loading in the assets? I'm using a self-deployed instance of DIVE (docker-compose). I looked through the docs and some of the previous GitHub issues, but couldn't find any clear instructions or tutorials. 

I saw docs for the REST API https://viame.kitware.com/api/v1#/ but I'm not sure if that's relevant.

Thanks!

**Comment by BryonLewis** [comment]
It can be done directly with REST API requests but that requires managing the file uploading which can be a bit cumbersome.
Luckily DIVE is based on [Girder](https://github.com/girder/girder) for its data management and REST API which includes something called the [girder_client](https://pypi.org/project/girder-client/).
girder_client is a python library that can be used to directly interface with girder and its REST endpoints to make scripting of actions a bit easier. 

I'm assuming you know a bit about the girder interface (localhost:8010/girder) since you managed to get the instanced deployed using docker-compose.  Just for background each item/folder has a `girderId` which can be accessed either through the girder interface or in DIVE it is in the URL.
![image](https://user-images.githubusercontent.com/61746913/228829980-95811b78-ae03-4af1-86be-c3df9385ca1a.png)
In the DIVE interface, it is in the URL.  **Note:**  the folderId is the same Id in the URL when viewing annotations.
![image](https://user-images.githubusercontent.com/61746913/228830156-5c4362ce-4fdc-4c1d-8768-6315e7f2a8f5.png)


To get data into DIVE it requires creating a folder, uploading the video file and any annotation files (VIAME CSV, or track JSON files) setting metadata on the folder and then hitting an endpoint `/dive_rpc/postprocess/:id`. 
The folder requires metadata of the data `type` 'image-sequence' or 'video' and also an annotation fps.  If the annotation fps is -1 during the postprocess event it will use ffprobe to check the video framerate and will match it.
These values can be set in the girder interface using the metadata tag on the folder.  Just remember to convert them into json so you are using int for the fps.
Once a folder has been processed and marked as a dive folder there is additional metadata added for ffprobe information.  The important part of additional metadata is `annotate: true`.  This marks the folder as a DIVE dataset so it can be opened in DIVE.
![image](https://user-images.githubusercontent.com/61746913/228830762-274a293b-b3d4-4427-b89b-4c0da598c5c0.png)

The `/postprocess` endpoint will do two things.
1.  It will take any CSV/JSON files and try to import them as annotations into the system.
2. If the `skipJobs` parameter is false it will attempt to transcode the video if the folder isn't already a DIVE folder.  If `skipTranscoding` is true it will attempt to skip the transcoding process if the file is an mp4 with h264 encoding (an some minor other checks).  If not it will transcode the video.  We transcode the video by default because that can sometimes help with badly encoded videos.

Okay, now that we have some background done I can link a sample `girder_client` script that goes through an input folder and searches for video and annotation files with the same base name and then uploads them to a DIVE instance.

[uploadScript.py
](https://github.com/Kitware/dive/blob/eb328c9f98ffe9504c874d4a996fe2704018266a/samples/scripts/uploadScript.py)

**Comment by SiftingSands** [comment]
Thanks so much for the detailed and quick response! I can confirm scripting uploads works as outlined. (finally had time to get back to this)

I was also able to automatically set parameters of detection attributes by adding the following, so that booleans are properly typed since it appears to default these to floats.
```
        attributes = {"detection_flag": {
            "belongs": "detection",
            "datatype": "boolean",
            "values": [],
            "name": "flag",
            "key": "detection_flag",
            "color": "#73bda8"}
            }
        # required metadata to be set on the folder for post processing to work properly
        gc.addMetadataToFolder(newFolderId, { 'type': 'video', 'fps': -1, 
                                             'attributes': attributes})
```

Do you know if I can automatically turn on "Draw Timeline" and set the "Timeline Filter" during the upload process? 
![image](https://user-images.githubusercontent.com/43226539/230912516-1cb4706e-2d0e-47c0-9f66-d7393a5fc5f3.png)

**Comment by BryonLewis** [comment]
>I was also able to automatically set parameters of detection attributes by adding the following, so that booleans are properly typed since it appears to default these to floats.

The import process makes a round 'best guess' as to the type of attribute it is importing.  I could see where it was confusing 0,1 values to be possible floats/numbers instead of boolean.  I'd have to double check but I believe there is logic where it should use JSON value true/false as a boolean by default.

> Do you know if I can automatically turn on "Draw Timeline" and set the "Timeline Filter" during the upload process?

This isn't something DIVE supports currently.  Although given some time I have some code that allows setting up and configuring multiple timeline graphs and then storing them in the 'configuration' much like the attributes templating.

> Is there also anyway to extend the "timeline" for detection attributes for multiple tracks? See the below where the timeline is only displaying results for a single selected track.

Currently, we only allow for the selection of a single track at a time, so the detection attributes for that selected track are shown.  The main barrier is the confusion of having all these editing modes and someone indicating to users they have multiple tracks selected.  Not to say it couldn't be done in the future I just need to think about it a bit more.

**Comment by SiftingSands** [comment]
Appreciate the clarifications.

Is there currently a feature to have the overlaid confidence values vary through a track? It looks like it's a static value defined by "confidencePairs". Not a big deal since I can stuff confidence values into the timeline for visualization.

**Comment by BryonLewis** [comment]
Sorry, the confidence values are meant to evaluate the track level confidence and not at a detection level.  You could create a detection level attribute and place the data in there (like you already stated).

Another option is to create individual detections (tracks of length 1) and have them each have their own confidence level.  This allows the confidence filter to work for filtering the displaying of those detections.  I don't the details of your data and if that would work better than having tracks with detection attributes.
