### ISSUE TITLE
Add documentation for how to run on AWS

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#156]

**Comment by subdavis** [comment]
Aside from providing a docker-compose, I'm not sure what this is intended to include.

We could write docs explaining how to get an EC2 instance, install docker, and run this app, but that would just be copy-paste from official AWS docs, official docker docs, etc that we would then have to maintain.   Anyone who knows what they're doing in AWS shouldn't need anything more than the compose file, and anyone who doesn't should probably go read official docs.

The only useful thing I can think to include is a systemd service to wrap our compose so that the app starts on boot.

**Comment by subdavis** [comment]
@mattdawkins I don't think we should be responsible for any more documentation than is provided in https://github.com/VIAME/VIAME-Web/tree/master/docker

Let me know what you think.

**Comment by subdavis** [comment]
We've provided a production docker-compose file and docker instructions.  We shouldn't write documentation about how to provision AWS resources.

**Comment by aashish24** [comment]
@mattdawkins was anything specific you were looking for on how to run on AWS? Was it for a customer  or Kitware staff?
