### ISSUE TITLE
[Ongoing] Desktop UI Discussion

### ISSUE THREAD

**Issue by subdavis** [Kitware/dive#417]
This is an issue to talk about the desktop UI.  It's just a place to dump screenshots as feature cadence is rapid.  Once a first version is released, we can close this and work on individual features.

![Screenshot from 2020-11-03 12-51-32](https://user-images.githubusercontent.com/4214172/98022382-8d3fb680-1dd3-11eb-9298-7aec804d67cd.png)
![Screenshot from 2020-11-03 12-51-44](https://user-images.githubusercontent.com/4214172/98022387-8dd84d00-1dd3-11eb-93a6-45db27a80a47.png)

**Comment by subdavis** [comment]
cc @aashish24

**Comment by aashish24** [comment]
@subdavis here are some very minor feedback to the already good looking UI:

1) In the first screen shot - it would be nice to show how many checks we run total (I am assuming it is 2) so we could say (1/2) GPU detection successful (2/2) KWIVER initialization successful so that user know that there were just two and both succeeded. 

2) I would have a clipboard copy option to the system information display so that someone can copy and paste that information in case that is needed for debugging in the future

3) In the second screen short - I wish we have the open buttons under the VIAME Annotation Tool and (left align) and then useful links on the same row (right align) (consider two column block, left block for buttons right block for links). The reason for that would be to minimize mouse movements when possible by keeping things to left (as that is from where the mouse most likely enter from the above)

**Comment by subdavis** [comment]
Jobs interface


![Screenshot from 2020-11-10 12-08-30](https://user-images.githubusercontent.com/4214172/98706988-85d95980-234d-11eb-8812-7721326a7112.png)

**Comment by BryonLewis** [comment]
This is just a list of comments from my latest review of the code.  They are mostly suggestions/questions and items we may want to deal with in the future.  I just wanted to log them here so we can start thinking about some of them.

1. Not a large issue but the built version on my PC seems to have some differing CSS styling than the `yarn serve:election` version.  Specifically the Jobs status indicator is misshapen.
    1. ![image](https://user-images.githubusercontent.com/61746913/98858197-3159db00-242e-11eb-8723-3132bedcfd64.png)
1. Job Suggestions/Questions
    1. Cancel or Killing a Job?  There seems to be no way to kill or cancel a running job within the system.
    1. Killing or notifying user of currently running jobs when they exit.  I noticed that jobs continued after exiting and only way I could kill was to manually kill them after.  
    1. Job history is only for the current session.  Should we store the jobs data and if they start it up again they can see previous jobs or currently running jobs
1. Video Folders - videos in the same folders will overwrite each other's annotations.  I don't know of a solution to this, but right now videos can't be a flat folder and annotated at the same time.  I believe this is the same for pipeline runs.
1. Some better warning/error messages when data is malformed or missing outside of the application.  I.E. a folder gets moved or renamed and the recents can't open it up.  
1. Minor Suggestions
   1. Recents being named to something like Data.  I had a brief time where I got confused on how to open new data because in my head recents were ONLY recently opened folders.
   1. Relates to above, but I think it may be beneficial to have  a tab or the VIAME logo or something dedicated to the current Annotation.  It may just be my use case of running short jobs and switching back and forth, but it was a bit annoying to go to Jobs Panel -> recents -> back to my data  everytime I wanted to check on the status of my job.
   1. I see how the 'view output` works in the jobs panel.  I clicked a couple times thinking that clicking on the open ones button would close it.  Very minor thing.
