### ISSUE TITLE
[FEATURE] If directory name is really short (<= 6 characters) also show last directory name in title

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#429]
For example on https://viame.kitware.com/#/viewer/5eb371608d01d968cc1642dd don't just show "Left" which has a lot of wasted white space but also the last directory name / Left

**Comment by subdavis** [comment]
Would involve an extra server request to get that name.   I don't really think this adds anything of value for a user.   

From a UX perspective, I generally disagree with idea that we should fill empty space with extra information just because it fits.  Signal:noise is more important.

### Some other points

* We're still planning on showing the image name of the current frame, most likely in the title bar somewhere, so that space might get used for something else.
* I strongly dislike the file browser metaphor.  See #252.

**Comment by subdavis** [comment]
Closing this this for now.
