### ISSUE TITLE
[BUG] Improve filename resolution for image sequence ordering

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#494]
There's a couple fringe cases where image sequences aren't loading in the right order. While hopefully people usually use things like 0001, 0002, ....  I've also seen (1), (2), ... (10), (11), which is loading out of order, e.g. attached below

![e1](https://user-images.githubusercontent.com/2353972/102089850-c1eb5880-3dea-11eb-8be9-9a2fbae79c8c.png)
![e2](https://user-images.githubusercontent.com/2353972/102089856-c3b51c00-3dea-11eb-8283-690ad4120c2b.png)
![e3](https://user-images.githubusercontent.com/2353972/102089862-c4e64900-3dea-11eb-9131-c7ece5e316f3.png)

**Comment by subdavis** [comment]
Images are being loaded in alphabetical order.  This is the order you get when you `ls` a directory on disk or open it in girder.

#454 already tracks adding an override for users to specify an order other than alphabetical, but it's probably not a good idea to try and come up with a more complicated ordering heuristic.  

Users should name their files so that they sort alphabetically or else provide a manifest file.

**Comment by mattdawkins** [comment]
They should yes, but they don't always, such as here. It's not unheard of supporting some special cases where ls fails. Our seal GUI currently loads these in the desired order - I think we should re-open but leave low priority (which it is at the moment).

**Comment by mattdawkins** [comment]
As does vpVIew which uses a Qt call to resolve ordering

**Comment by subdavis** [comment]
Idea: just regex extract all digits `\d`, parseInt, and sort them.
 
If no digits are found, fall back to alphabetial.
