### ISSUE TITLE
Make configurable settings and detection/track attributes be user-specific, not global with no access restrictions

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#54]
People keep on changing them (ideally it would show whatever attributes are a part of the currently loaded displayed video [if any] + user attributes

Applies to detection and track attributes

**Comment by subdavis** [comment]
In an ideal world, these attributes are actually dataset-specific, right?  You might have some datasets where an attribute applies and some where it doesn't?

I think it would be really nice to have the ability to create named attribute-sets that they can then attach to datasets.  So you create a list of attributes and name it, then you choose on each video what collection of attributes it applies to.

Perhaps there's a global namespace for attributes, so you create a set and everyone can use it.

Cloning attribute sets would be necessary, to create small variations on a common theme.

I think having them unique to each user is a good place to start, but for "lab managers" who create a bunch of data then have interns do annotation, will it be a problem that each intern could potentially have different attributes?  Or even worse, the same attributes with different capitalization because they entered them differently?

**Comment by mattdawkins** [comment]
Sometimes they are dataset specific and sometimes user specific. Ideally any attributes associated with the dataset (have been entered by any user on a particular dataset) are shown, alongside any that the user has entered in their own settings as potential fill-in options. Agree that unique to each user (their own settings) is a good place to start, as we're likely to add other settings as well.

**Comment by BryonLewis** [comment]
If I'm understanding this correctly.  We would move the 'Settings' attributes from a global scope to a user specific scope.  Where each use as their own list of custom attributes that can be used.  I don't know exactly how we want to set this up.  If we use a private folder with a file indicating different attributes.
So this:
/home/bryon/dev/wiki/VIAME-Web.wiki/images/Attributes/AddAttribute.png
![image](https://user-images.githubusercontent.com/61746913/92733083-3ffc1700-f345-11ea-9515-a8d9bba1a13b.png)
Becomes user specific.

Secondarily in the editor for the specific project the dropdowns for attributes will contain all of the user's attributes along with any already set attributes by other users.  So if User B decides to add a track attribute "Diseased" and sets it somewhere in the project any other user will be able to set a Diseased track attribute on any track in the project.  These lists of available attributes will be unioned with the list of User A's attributes.  So that way each user has their own list but it can be shared in projects.
This:
![image](https://user-images.githubusercontent.com/61746913/92733188-6457f380-f345-11ea-91da-c36abcd643d3.png)
is a union of existing track attributes and the user atributes where they can select differing options.

Handling Conflicts:
Conflicts will occur between attributes which have the same name.  Need to decide on how to handle that and how to update the track attributes that exist if there is a conflict.

Text String Lists won't import:
There would be no mechanism to support the text, dropdown types where there were pre-chosen categories unless all of those categories are represented in the data.  We can generate list from the already provided values and use that but requiring a list of unused text values would necessitate building a data storage item for each folder outside of the existing track.json.

**Comment by BryonLewis** [comment]
Went through and discussed with Brandon about the best way to implement this.
A document was created which describes the system and how it should be implemented:
https://docs.google.com/document/d/1hHnfUsSe2twPEyWd8xMB58z8Ks9Maoz1yFFmHjuIACg/edit?usp=sharing

Core Idea:  We use a templating system which will take a previous dataset and use it as a basis for a new dataset.  As long as you have read access to the system you should be able to access the types as well as the track/detection attributes.  So attributes and types live with a dataset and can be combined with other datasets to create a template that is used.

Phased Development:
We can develop this in phases beginning with the sharing of types and type styling, then start working on the attributes.

**Comment by BryonLewis** [comment]
Had some brief thoughts about how to implement this in the desktop version of VIAME.  It would involve switching items over to using the `meta.json` file instead of a backend service for attributes.

Tasks:

- Desktop Import CSV - update meta.json to include the track/detection attributes when importing
- Attribute type inference - attempting to infer the attribute type from a summary the possible results in the CSV, side with more flexibility (string) if unsure
    - I.E - If all items are of type number I can assume it is a number, if multiple items (don't know the break point of N > X) have the same string values I can assume a list and if not I can assume a regular string. 
- Below is where it could diverge:
- **Option 1:**  Change desktop version so GET/POST `/viame/attributes` interacts with the JSON metadata instead of a global datastore of values.
    - Pros: Smaller change on desktop only to get the system working properly.  Not changes to the front end `trackDetails` system because we are intercepting the calls and creating/deleting/modifying based on the calls.
    - Cons: Eventually we are moving attributes into meta.json for both desktop and web 
- **Option 2**: Change the attributes panel (DESKTOP/WEB) so that it deals directly with `meta` instead of the backend service.  Similar to the way in `customStyling` works.  Something like a useAttributes hooked to the metadata and increments the save on modification.
    - Pros:  This is where we are heading where the attributes are stored in the meta field of a project so it can be shared anyways.  At some point it is going to be needed on the web version
    - Cons:  A bigger change that will require at least an initial call to the existing `viame/attributes` to populate the JSON file with the current global values.  A good sign is that the current global attributes on the viame.kitware.com server includes only 2-3 attributes.  This will also require some significant additions to the front-end code outside of the desktop stuff .

**Comment by subdavis** [comment]
> Desktop Import CSV - update meta.json to include the track/detection attributes when importing

This only has to be done once at import right?  Because attributes will only be created/removed through the attribute management panel.  In other words, you don't have to keep these in "sync", or worry that a track upsert operation will introduce a new attribute.

I'm good with this.

> Attribute type inference - attempting to infer the attribute type from a summary the possible results in the CSV, side with more flexibility (string) if unsure

Perhaps start with an unsophisticated solution first here.

> Change desktop version so GET/POST /viame/attributes interacts with the JSON metadata instead of a global datastore of values.

It doesn't do this right now. This endpoint doesn't even exist.  Did you mean web?

> Change the attributes panel (DESKTOP/WEB) so that it deals directly with meta

There's another con here.  It decreases granularity and requires more complexity to keep consistent.

If you deal directly with meta, you have to pass the whole object, and the server has to replace the whole thing.  If two people are working on a data set, they could erase each other's work just by each adding a different new attribute.   This is part of the reason I changed the track POST payload to be `{ upsert: [], delete: [] }`.

I don't really care that much about the API structure, but I like having the ability to transmit only the changes and none of the duplicates.   Keeping the API as it is in the first round of changes seems preferable.

The same argument could be made about customTypeStyling, but attributes are more important / higher stakes than user style preferences.

-----------

Anyway, great assessment, I prefer Option 1.

**Comment by BryonLewis** [comment]
Thank you for the feedback.

> > Change desktop version so GET/POST /viame/attributes interacts with the JSON metadata instead of a global datastore of values.
> 
> It doesn't do this right now. This endpoint doesn't even exist. Did you mean web?

For some reason I thought this endpoint was already templated (It might of been before the refactor, I don't remember).  So it looks like I would have to add it to the desktop version.

>If two people are working on a data set, they could erase each other's work just by each adding a different new attribute. This is part of the reason I changed the track POST payload to be { upsert: [], delete: [] }.

Good point I forgot about that.  This seems similar to the case in which you launch a pipeline, mess around with data while the pipeline is running and then either reload/save after the pipeline is finished.  May be necessary to implement a notification system for when data is changed outside of a users control and asking them if they want to save current data or load the new data.  Could also be tied into a 'history' system to go back considering we save backups of each save.

**Comment by subdavis** [comment]
@BryonLewis is this issue also complete?

**Comment by BryonLewis** [comment]
I would say the strict definition of this would be complete.  I have that other issue which is tracking the planning regarding the larger picture 'Attributes System' (csv import, export, web/desktop sharing and user sharing).  As long as you're good with it I think this can be marked as closed.

**Comment by subdavis** [comment]
There are other open issues about the Attribute system.
