### ISSUE TITLE
[FEATURE] Allow training on both GPUs on viame.kitware.com

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#563]
To prevent 1 user from using the gpus for days at a time

**Comment by subdavis** [comment]
This is not technically feasible given how our pipeline queuing works.

Celery and Girder Worker work by writing job payloads into a rabbitmq pub/sub queue.

They're written into the queue, and run as they come out the other end.

We have 3 "topics" for pipelines, trainings, and transcoding. 

A round-robin would involve a queue for every user, which we couldn't implement using rabbit, so we'd have to implement it with a database and rest endpoints.  

It would essentially involve abandoning girder worker, which would be very costly for not much benefit.

There are other things we could to do mitigate the slowness, like allowing the training GPU to run pipelines if there are no training jobs to run.

**Comment by subdavis** [comment]
I spent an unwise amount of time trying to find a good option for this.  There isn't one.

What we want is to have all workers listen to the pipelines queue, but the training worker prioritize training messages if they are found.  RabbitMQ (py-ampq) doesn't do this.  Redis queue does, but we'd have to change over to a different pub/sub provider, which carries risk.

Best option is probably just to let both GPUs take pipline tasks and relax our requirement that training takes priority.  That would be  a better allocation strategy than we have right now.

We could also use a priority queue, but we'd have to allow the small GPU to take training runs as well, because priority only works within a queue (and not between them).

Anyway, I'll let you decide how to proceed @mattdawkins .

**Comment by subdavis** [comment]
Bump @mattdawkins I recommend we open up both GPU Resources for both pipeline and training tasks.  As it stands, we're taking resources away from customers with no upside / benefit to others.

**Comment by mattdawkins** [comment]
Both GPUs can be opened up for testing, though I think one should still be devoted just to training for the time being the main issue is if someone starts a training run on both that will hold up testing

**Comment by subdavis** [comment]
done in #616
