### ISSUE TITLE
species types as attribute confusion

### ISSUE THREAD

**Issue by subdavis** [Kitware/dive#59]
"Another thing that's come up is people keep on adding species types as attributes and we'd want to make sure it's highlighted in the document which is which"

@mattdawkins please clarify what different parts of the app are being confused and what needs to be communicated.  As far as I'm aware, there's only one way to provide freeform text.

**Comment by mattdawkins** [comment]
In settings you can set the name of detection and track level attributes (which are different than the freeform types next to the tracks which are supposed to be species IDs). Attributes are independent of species, things like fish_length. is_fish_swimming_straight, etc...

I think besides in the documentation it might even make sense to put text in the settings section so it's clear, describing what attributes are.

**Comment by subdavis** [comment]
![Screenshot from 2020-04-16 11-29-35](https://user-images.githubusercontent.com/4214172/79481467-8b500a80-7fdd-11ea-9241-3f365000c4c8.png)

I didn't realize this feature even existed.  The confusion makes sense now.   How would you describe the purpose of track and detection attributes?  Are they just considered to be "everything except species?"

**Comment by mattdawkins** [comment]
"Attributes other than species" would be sufficient then giving examples such as fish_length, is_straight, etc... if adding a description

Looking in the above "on bottom" is the only thing there that should be an attribute. Since attributes are global right now, non-admins should only be able to add attributes, not delete or edit unless attributes become user/dataset specific.

**Comment by subdavis** [comment]
resolved by #583
