### ISSUE TITLE
[FEATURE] Desktop: de-list unreferenced datasets in remembered dataset lists

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#593]
When the data storage location changes in settings, items in the recent list are invalidated but remain and then get re-imported with the same name. It seems I collect a couple duplicates

![why_two](https://user-images.githubusercontent.com/2353972/108857621-46abdd00-75b9-11eb-8f40-0d3e71784418.png)

![old_job](https://user-images.githubusercontent.com/2353972/108857627-4875a080-75b9-11eb-8e44-d4f03d67c349.png)

**Comment by subdavis** [comment]
This is discussed in https://github.com/Kitware/dive/issues/417

**Comment by subdavis** [comment]
Having things automatically disappear would confuse users. 

When a user tries to open a missing dataset, I think it would be better to:

* Ask them to re-identify the source data, or
* Allow them to delete the dataset, acknowleging that any annotation data will also be lost.

Would this be OK?

**Comment by BryonLewis** [comment]
So to address this I'm going to add in:

- Deletion button in recents to remove datasets that are no longer needed
- On loading of an incomplete dataset you can point the folder again to a new location or delete it like Brandon suggested op there.
- There was talk about duplicate named items in the datasets from subsequent imports.  We have the warning currently but I think I'll add modification date to the recents list to help distinguish.  A secondary thing would be to allow a user to overwrite if the same folder is being used instead of generating a new dataset?

**Comment by BryonLewis** [comment]
Thoughts?
Last Access is updated each time a user opens a dataset so the Recent's list is truly sorted by Recent and last access
![image](https://user-images.githubusercontent.com/61746913/125986653-09007086-43e3-41e0-8d03-83fcf44b1c7b.png)
