### ISSUE TITLE
[FEATURE] Normalize number of lines in Web Interface and other VIAME apps

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#636]
Customer requested to always have, no matter of the presence of metadata, and between desktop and web versions the same number of commented # lines in a csv.

We could either merge the metadata and written by so and so lines (my recommendation and making there always be 2) or always have 3

![desktop vs web output](https://user-images.githubusercontent.com/2353972/110994886-80b20880-8347-11eb-9478-d694a0d096e8.PNG)

**Comment by subdavis** [comment]
They're asking us to change the syntax to eliminate comments and replace them with a fixed length header.  If this changed, `#` would no longer have lexical meaning.  It might confuse people, looking like we support comments when we don't.

If we're going to commit to a fixed length header, I'd rather have 3 lines for future needs than packing multiple kinds of data into a single line.

Also, parsing the metadata json will be much, **much** easier if we can try to parse the entire line as json rather than having to do parenthesis matching or some kind of nasty lookahead regex.  Alternatively, we could make the written-by linepart of the json 

i.e. `# { "fps": 30, "written_by": "identifier" }`

**Comment by subdavis** [comment]
Use two lines, embed written-by information in metadata of second line.
