### ISSUE TITLE
[FEATURE] Unauthenticated mode

### ISSUE THREAD

**Issue by subdavis** [Kitware/dive#727]
Show off features and make the barrier for data exploration lower by allowing anonymous users to browse and launch public data.

**Comment by subdavis** [comment]
This feature is mostly for reviewers / managers

We need an explicit "view-only" mode that hides all the edit GUI elements.

**Comment by subdavis** [comment]
# Needs discussion

We have 2 similar but slightly different asks of this feature:

* We would like the ability to launch datasets in a mode that does not allow for editing.
* We would like to be able to launch and share links to public data that people can view without logging in.


## Options

* Just disable the save button, and let people play with the full UI controls client-side.  This is preferable for the second case because it allows us to showcase some of the powerful editor features to new users quickly without registration
* Disable all "mutation" controls, such that the environment is truly read only and a user cannot make any changes to the data.

This will also probably impact any plans for #614.

Just disabling save is significantly easier and I'd suggest doing this as a first pass.

## Other questions

I believe MEVA wants this for desktop.  How would you expect to signify to the application that you want your user in review mode and not able to make changes?  Unlike web, desktop has no permissions system.   The only thing I can think of is to put a toggle in the settings page.

What is the purpose of this?  To make the data easier to look at or to prevent accidental changes?

**Comment by collinsr** [comment]
MEVA would probably prefer the disable-mutation options, but either could work. The overall goal is to reduce opportunities for errors in transition situations, where we will have little or no opportunity to provide advice and users will have little or no opportunity (or motivation) to reach back for help. For example:

- They may be demoing the system to a local VIP (or even just a co-worker), accidentally click EDIT, get confused, and everybody just goes "Whatever, this is weird, what's the next item on the agenda"

- They may hand it off to somebody who hands it off to somebody else who hands it off to somebody who never got the documentation and thinks editing the results, since it's possible, is therefore somehow meaningful

...generally just looking to let the interface manage expectations since we won't always be there to do it ourselves.

**Comment by subdavis** [comment]
@collinsr thanks for the clarification.

Because this is desktop, there's really no way of knowing when a user launches the application or opens data that they wanted to open it in read-only mode.  How would you want to accomplish this?  It would be the user's responsibility to turn on their own read-only mode to protect themselves.

I'd love to be able to set a "protected" flag on the annotation file or something like that, but we didn't think ahead when designing the file format.  Fixing that mistake to enable extensions like this is on our list, but unlikely to happen short term.

**Comment by collinsr** [comment]
If read-only mode can be a command line parameter / environment variable / etc, we would ship a shell script / batch file that invokes the tool passing that parameter, or something like that, and then in our instructions we'd tell them to launch the tool via that pathway. If somebody is feeling adventurous enough to explore beyond our instructions and inadvertently enables editing, more power to them; this is more about minimizing possible distractions for somebody trying to just follow (possibly second-hand or hearsay) directions.
