### ISSUE TITLE
[FEATURE] Toggle Keyframe hotkey

### ISSUE THREAD

**Issue by subdavis** [Kitware/dive#728]
user request.

Hotkey to toggle keyframe both inside and outside a track bounds where the outer bound keyframe has interpolation on.

When annotating certain targets, it's nice to periodically drop a keyframe without adjusting the bounding box as a checkpoint.  This is helpful for targets that don't  move for a while then move.

**Comment by BryonLewis** [comment]
I assume besides toggling keyframes at anytime using a shortcut you wanted to lock down in-progress pseudo annotations from the interpolated mode?

I mean stuff like this:
![image](https://user-images.githubusercontent.com/61746913/123150301-3523f600-d430-11eb-8746-042738ef50af.png)
Where if you hit the 'K' key or keyframe button it should lock down this temporary location as an actual keyframe instead of requiring the movement of the box to lock it down?
