### ISSUE TITLE
[BUG] When importing csvs for image sequences rely on filename first then ID

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#733]
It should probably only use filename if everyone is valid and matches an upload image (to prevent issues if users annotated them in a different order)

Should be both web and desktop

**Comment by subdavis** [comment]
@mattdawkins  for this CSV image ordering alignment issue, there are really only 2 possible approaches:

1. Expect that this will only happen on detection datasets with no temporal relationship.  Detections only, no tracks.  Just reorder the annotations based on our expected image ordering
2. Require an image-list file to be uploaded alongside annotations.  There's no way to guarantee that a given annotation CSV will have 100% coverage (that every image will appear in the file and be sufficient to reconstruct the desired order)

I would prefer to do the first thing, particularly because this issue should fade as less an less people use view.  If any of the people who have hit this had tracks instead of just detections, we'll have to do the second thing.  As a bit of a catch-22, doing the second thing would not have solved Randy's problem because he lost his image list.  In his case, either (1) or a call with you to manually sort out the problem seems appropriate.

what do you think?

**Comment by mattdawkins** [comment]
I don't see this as strictly a VIEW issue, because someone can still generate annotations outside of any interface (DIVE, VIEW) via external means, and want to import them or train models on them in whatever order. Some other potential fringe cases are users wanting to extend sequences themselves to an existing sequence (add more images either before or after alphabetically), append 2 different csv files together manually without updating the image ID values (what might have happened here as well in one instance, though that comes with it's own risks), or just verify what the CLI train tool is seeing which follows the filename first load ordering (frame ID as fallback).

The two groups that have had this issue so far have been detection/full frame only people technically, though the CSV contains all information necessary for the prior cases in the case of containing tracks. Is there a DIVE implementation detail making it difficult in the track case?

Some of the potential caveats is that the train tool ignores timestamps in column 2 (anything containing at 1 or 2 ":" characters and a period) because they would be for videos (though theoretically there could be consistency checks on column 2 for videos too but we don't do those), ignoring full paths always, often ignoring extensions (latter much less important).
