### ISSUE TITLE
[FEATURE] Batch download items in web UI

### ISSUE THREAD

**Issue by nrsyed** [Kitware/dive#812]
**Describe the bug**
If a single item is selected in the web UI, the Download button is enabled and it can be downloaded. If two or more items are selected, the Download button is disabled and grayed out.

**To reproduce**
1. Select an item via its checkbox
![viame_batch_dl_1](https://user-images.githubusercontent.com/11943352/122271254-38a60300-cead-11eb-8241-dfb829fb0679.png)

2. Select another item
![viame_batch_dl_2](https://user-images.githubusercontent.com/11943352/122271274-3d6ab700-cead-11eb-8224-7d775d1930c8.png)

**Related data**
https://viame.kitware.com/#/folder/5e4c2817a0fc86aa0315b1a1

**Expected behavior**
Allow download when multiple items are selected.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: reproduced on Brave 1.25.72 (Chromium: 91.0.4472.101) and Chrome 91.0.4472.101

**Comment by BryonLewis** [comment]
This does need to be added in, but a quick workaround for now is to use the girder interface:
https://viame.kitware.com/girder/#collection/5e4c256ca0fc86aa03120c34/folder/5e4c2817a0fc86aa0315b1a1
Click on the folder you want and then the options next to the top-level checkbox to download the checked resources.  This will grab the entire folder structure.  You probably don't want the zips sub folder.
![image](https://user-images.githubusercontent.com/61746913/122273207-2d53d700-ceaf-11eb-808a-3994eafc7c53.png)

**Comment by subdavis** [comment]
Changed to a feature request.

The fix depends on what your goal is.  If you want the viame CSV, you should probably just write a python script to call the REST api directly.  If you just want the media, you can do what Bryon suggested.

Note that the workaround won't give you a detection CSV because it requires a special export procedure.  There's not really an easy way to do this, because generating the export in a request is expensive. 

In general, I'd recommend scripting this rather than using the browser.

See https://viame.kitware.com/girder/api/v1#!/viame95detection/viame_detection_export_all

**Comment by subdavis** [comment]
This feature request has been completed and will be deployed Thursday Feb 10 at 2AM est.
