### ISSUE TITLE
[BUG] import button from viewer shows no loading progress, seems to freeze.

### ISSUE THREAD

**Issue by subdavis** [Kitware/dive#873]
Make it show some kind of progress indicator.

**Comment by BryonLewis** [comment]
I believe the freezing it related to the clearing of the previous tracks.  Freezing doesn't occur on large file imports.  It only occurs if you are importing into a large dataset.   I did it using the available deleteTrack system to prevent issues.  There should be a way to do this be just resetting the trackMap and other items and allowing the system to do GC.  I'll do some testing.

**Comment by subdavis** [comment]
> I believe the freezing it related to the clearing of the previous tracks. 

Why even bother clearing the previous tracks? Why not just trigger a lifecycle hook on `Viewer.vue`

**Comment by BryonLewis** [comment]
Just organizing (somewhat) my thoughts on this and trying to determine the best solution:

Case for Viewer Reload:
- ensures that the entire system is reloaded causing a page redraw
- Clearing Tracks may have some left over data that I'm not accounting for which could cause an issue.

Case for Clear Tracks:
- `reloadAnnotations` is a provided function in the `useHandler` that is used to reload the annotations through the import methods.    It would have to emit a signal up ViewerLoader.vue to tell the key of the Viewer to change to reload it.
- Using Viewer.vue Reload requires performing updates in two ViewerLoader.vue files for the same functionality (Desktop/Web)
- Desktop Stereo Camera relies on the current camera being know in the Viewer.vue and having it load the different sub projects for the current ID I.E `stereo_xyzabc/cameraLeft` and then when switching to cameraLeft it knows to clear the tracks and load the detections/metadata for `cameraLeft` while maintaing it's current list of cameras for the other ids.  This logic would have to be moved into the two ViewerLoaders to handle this.  It's doable but a little more time costly.
-  Changing the load method would require having the viewerLoader.vue know about the camera metadata, that is okay because the store contains it already.  The downside is that camera changes in the viewer will have to emit another signal back up into the viewerLoader.vue to change the camera page and cause an entire refresh of the Viewer.vue with the correct camera.
-
