### ISSUE TITLE
[FEATURE] Per-track-type threshold sliders to replace global detection threshold

### ISSUE THREAD

**Issue by subdavis** [Kitware/dive#897]
@collinsr please complete

**Is your feature request related to a problem? If so, Please describe.**

**Describe the solution you'd like**
A description of what you want to happen.

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Additional context**

**Comment by mattdawkins** [comment]
+ import / export of per-type levels but that might be a different issue

**Comment by subdavis** [comment]
![Screenshot from 2021-09-17 14-52-25](https://user-images.githubusercontent.com/4214172/133839783-262d22a6-181f-4717-b402-a47b515bceff.png)

Can I verify with @mattdawkins and @BryonLewis  and @collinsr that this is the right idea?

This pane is closed by default and can be dismissed when it isn't needed, which should be most of the time.

**Comment by BryonLewis** [comment]
- I know we didn't arrive on an exact mechanism but when closed if a type has a non-default confidence value I think it needs to be indicated in the type list in some way. 
- Possible styling matches for colors between the two panels (I.E. type color matching because species names).  I'm assuming you're in progress of doing this already.
- :+1: :+1: :+1:  non-vuetify sliders :+1: :+1: :+1:
