### ISSUE TITLE
[BUG] DIVE-Desktop selects detection not track file when both produced

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#939]
In the latest version of DIVE desktop in VIAME if a computed_detections.csv and computed_tracks.csv were both produced by a .pipe then computed_detections is displayed but computed_tracks should take priority

**Comment by BryonLewis** [comment]
@mattdawkins I think the fix was relatively simple.  I just want to confirm that no detector pipelines will create an empty `computed_tracks.csv` file.

**Comment by subdavis** [comment]
> I just want to confirm that no detector pipelines will create an empty computed_tracks.csv file.

Why would this matter?  By empty, do you mean zero bytes or empty not including header? 

While we're talking about it, it might be preferable to run both files through CSV parsing within the worker job instead of relying on postprocessing, which would move heavy CPU work out of the server  request thread?

**Comment by BryonLewis** [comment]
This is on desktop, I believe the server is doing the proper thing.  So it isn't in a request it's on the process job 'exit' that this is done.

It's calling this: https://github.com/Kitware/dive/blob/841e3479a1e60744d15d3c44d534878751bb0cd6/client/platform/desktop/backend/native/common.ts#L538  on a computed_detector.csv and a computed_tracks.csv in a for loop.  The order just needed to be swapped so that it did the tracks second.  The current way it is setup if you swap the detector/track output values from running the pipeline: https://github.com/Kitware/dive/blob/facf81612ff2f0b0f223b4ae103b5bcd96b73d4a/client/platform/desktop/backend/native/viame.ts#L184
It will fix the issue as long as the `computed_tracks.csv` is non-existing.  Which it is in a few tests that I did.
