### ISSUE TITLE
[FEATURE] Don't query user to save if outstanding edits, but a pipeline is running on data

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#991]
If you run a pipeline on data (which is currently running and unfinished), but then the user makes some edits (or has some outstanding edits they haven't saved) to data and tries to leave the page (e.g. go to jobs panel) it will ask the user if he/she wants to save the outstanding edits, though my concern is that the pipeline runner will (and should) displace those changes so the save is redundant, and also if the save happens after pipeline execution finish, would it over-write the pipeline results?

**Comment by BryonLewis** [comment]
might want to take a look at this test branch I did when messing around with the job notification update PR. https://github.com/Kitware/dive/tree/pipeline-job-running

**Comment by BryonLewis** [comment]
I feel as if we need to properly implement ReadOnly Mode where it disables items in the interface and explains why.  Disabling stuff like deleting/adding new tracks.
I think that as a consequence of that we may need a new wrapper for buttons/icons that enable a disable state while also including a tooltip reason as to why items are disabled.

**Comment by BryonLewis** [comment]
That's what I did for the above demo, it's just that once a button becomes disabled it removes tooltips because the v-on doesn't trigger properly.  So you have a button disabled with no indication as to why the button is disabled.  I would have to wrap the button to make it styled as disabled.  I could also wrap each button in a span tag so the v-on still triggers to display the tooltip but the button is truly disabled..

**Comment by waxlamp** [comment]
I guess I forgot to say the rest of my thought: a red or yellow banner across the top of the viewport with information like "you are in read-only mode" followed by an indication of how to get out of that mode might cover all cases. Then you wouldn't need to add redundant info to every single disabled control, and there would be a central way to understand what's happening. (I'm definitely following the excalibur idea here of displaying in text the "mode" information).

**Comment by subdavis** [comment]
I like it.  I think the only thing I'd add is a link directly to the pipeline logs (in girder) from the "A pipeline is running" dialog.  

There is one other issue:  Cancelling. 

Pipelines can get stuck in the cancelling state because VIAME doesn't respond to signals, so the pipeline will continue to run to completion, then the whole job will fail because of an invalid state transition (Can't move from canceling to uploading data). 

In order to merge this in, we probably need to first make sure that the cancel button always works.  I think we found some python OS function a while ago to force kill a whole PID tree, but I dont' remember.

**Comment by BryonLewis** [comment]
So I added in a Read Only Mode Display with a tooltip explaining that it is read-only mode.
I also added in a View Running Job which will link to the Jobs page on desktop and will open the girder/#job/{jobID} page on the web version.
Also fixed the overflow issues with long dataset names
![image](https://user-images.githubusercontent.com/61746913/153230051-3e72b2c2-db1c-4ec8-aa0f-42d931d94f12.png)
![image](https://user-images.githubusercontent.com/61746913/153230129-6e9c4af8-4b4b-4a1f-8b91-037880cc2543.png)

**Comment by waxlamp** [comment]
This looks really nice!

**Comment by waxlamp** [comment]
@faiza-a, could you give some quick feedback on Bryon's design here? Just a sanity check for any obvious improvements we could make (with a more comprehensive review of the full UI happening more slowly, as it already is). Thanks!

**Comment by faiza-a** [comment]
I think it's looking good and serving the purpose.
Adding an info icon would make it more prominent for user that the 'chip' is hoverable.

![Group 843 (1)](https://user-images.githubusercontent.com/61198087/153316173-26b3b49c-8c80-48da-bb3e-41409f76fb9a.png)

May also use the horizontal space to make more information visible. (but this could also look more crowded)

![Group 844 (2)](https://user-images.githubusercontent.com/61198087/153317040-473e74b4-c2f0-436e-9f4e-455e6d86953f.png)

**Comment by waxlamp** [comment]
@BryonLewis, I think the info icon addition is a good idea--do you agree?

Displaying more info using the horizontal space is generally a nice idea but I think we need to better understand the effect of doing so on the UI, so let's hold off on that idea for now.

**Comment by BryonLewis** [comment]
Yup, I had a `?` icon in there at one point and it didn't feel right.  The info icon looks much better.  I'll ad it in.
