### ISSUE TITLE
[FEATURE] Improved training pipelines sorting in train drop down (Web and Desktop)

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#999]
Ideally anything with the word "default" in it would be listed at the top of the menu first [with the object detector default the default selection], then all other entries would be alphabetically sorted after that, e.g. custom pipelines. An alphabetical sort, without the defaults first, would also possibly be better than it is now on web because you have to read through each one individually now to find what you actually want. (rehash of https://github.com/Kitware/dive/issues/518)

**Comment by waxlamp** [comment]
It seems like maybe the order and manner in which pipelines are displayed to the user should be explicitly configurable. Something universal like "alphabetical sort" is suitable, but one-off schemes where everything with "default" in the name appears first seems trickier to include as default behavior.

@mattdawkins, as a workaround, can you rename the default pipelines to start with `[default]` so that they naturally appear first in alphabetical sort? In the meantime, we can discuss approaches to making this more configurable per-deploy.

**Comment by mattdawkins** [comment]
We want things to be sorted by the type of training they do, which right now alphabetical will do that fine, with the one exception being train_detector_default should always be the default first option in the list, as some people just ignore the configs altogether and that's should be the most commonly used pipe. As a step forward but much more minor, the 'defaults' would be listed at the top of their respective sections. For example right now it looks choatic in the below,

![Screenshot from 2022-02-02 15-09-35](https://user-images.githubusercontent.com/2353972/152230238-b5575b0d-afc6-4b00-b374-61b7242324ff.png)

Can't find anything without reading through everything. I think this schema would look best

train_detector_default
train_detector_darknet 
train_detector_netharn_cascade
...
train_frame_classifier_default
train_frame_classifier_*
...
train_object_reclassifier_default
train_object_reclassifier_*

but it wouldn't be so bad if the defaults for each type was intermixed with the regular configs as a first pass

**Comment by mattdawkins** [comment]
Alphabetical sort with the exception of train_detector_default being first in the list takes care of most of the above cases
